adds testing endpoints
Lambda-School-Labs/story-squad-ds-b pull request #6
Opened 2021-02-18 18:55 UTC by James-Hagerman

# Description

Replace with description of PR

## Type of change

- [✔ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [✔ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [✔ ] No
- [ ] Not necessary

## Checklist

- [✔ ] My code follows the style guidelines of this project
- [✔ ] I have performed a self-review of my own code
- [✔ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [✔ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [✔ ] There are no merge conflicts

2021-02-19 17:20 UTC, jproctor-rebecca requested changes

2021-02-19 17:20 UTC, jproctor-rebecca commented on app/api/submission.py
>          # fetch file from s3 bucket
thank you for adding the inline documentation - it is the small attention to details like this that create transfer of knowledge in the moment and through time on a project

2021-02-19 17:20 UTC, jproctor-rebecca commented on app/api/submission.py
> +#     return JSONResponse(status_code=200, content=response)
Do we need to leave commented-out code in the code? or should it be cleaned up?

2021-02-19 17:20 UTC, jproctor-rebecca commented on app/api/submission.py
> +
lines 54-108 
during product review, we decided to leave this connected to the GV API and just get the credentials until MVP has been met on the model
please add this code back
thank you

2021-02-22 22:03 UTC, EEdwardsA commented on app/api/submission.py
> -    SafeSearch API and flags if explicit content detected.
Are we sure we want to remove SafeSearch functionality?

2021-02-23 21:59 UTC, closed without merging